version: '3'
services:
  server:
    container_name: backend
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/app:/www/app/bwitter/server/app
    command: npm start

  client:
    build: ./client
    expose: ${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/www/app/bwitter/client/src
    links:
      - server
    depends_on:
      - "server"
    command: npm start
