version: '3'
services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/app:/www/app/bwitter/server/app
    command: npm start

  client:
    build: ./client
    expose: ${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./client/src:/www/app/bwitter/client/src
    links:
      - server
    command: npm start
