name: Lint

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run-linter:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd client && npm i && npm run lint
      - run: cd server && npm i && npm run lint
